name: CI/CD pipeline
on:
 push:
  branches:
   - main
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3
     with:
      node-version: 16
   - name: Install Dependency
     run: npm install
   - name: run tests
     run: npm test
   - name: deploy to production
     run: npm run
